### ISSUE TITLE
Suggestion for project quality metrics

### ISSUE THREAD

**Issue by matt-oakes** [react-community/native-directory#33]
I think this website is a really well-needed resource and thanks for creating it.

One of the key bits for me is the project health feature. I think the simplistic score you have currently is a great start, but I was reminded of the great project quality feature that the Cocoapods (iOS dependency manager) directory has. You can see an example of a libraries quality page here:

https://cocoapods.org/pods/AnimationSugar/quality

By default, it starts a library with a score of 50 and then adds and subtracts from that to get the final score. Things like "being very popular" get an addition and others like "using a GPL licence" (which is arguably incompatible with the Apple App Store) result in a subtraction from the base score.

On the page I linked above, press on the "show metrics not applied" to see the full list of possible metrics. They have also documented how this system works and the theory behind it here:

https://guides.cocoapods.org/making/quality-indexes

Overall, I think a system like this would be a great way to measure the health of React Native libraries as well. Let me know your thoughts and I'm happy to help out if this is a direction you want to move in.

**Comment by jimmylee** [comment]
@matt-oakes you are great, @brentvatne has shown me that quality index score before and I would totally love to do the same thing here. If you have the bandwidth to help out it would be super appreciated 🙌 

We didn't marry any ideas when we first started this project, so we're always down to make anything more useful, thats the most important thing.

**Comment by matt-oakes** [comment]
Thanks! Here's a rough plan for the scoring system:

**Popularity:**
Popularity rating = (contributors * 90) + (subscribers * 20) + (forks * 10) + stars
Popular if popularity rating > 1500: *+10*
Very popular if popularity rating > 9000: *+30* (popular will also be applied, so it's really +40)

Explanation: *The score allows us to weight numbers which require more work from a user to be higher than others. Starring is low effort so contributes less, whereas contributing is very high effort and contributes more. This was shamelessly borrowed from Cocoapdos, so we might need to adjust the weightings and thresholds to make sense for React Native projects.*

**Readme:**
Use [readme score](https://github.com/clayallsopp/readme-score-api) to get a score for the README.
Readme score > 75: *+5*
Readme score < 40: *-5*
Readme score < 25: *-10*

**Other:**
Open issues > 50: *-10* (popular libraries might have a lot, but the popularity score will negate this penalty)
Uses GPL licence (incompatible with Apple App Store): *-20*
Is recommended library (gold star in `react-native-libraries.json`): *+20*

**Calculating the final score:**
I think the final score should be from 0 to 100 as it is currently. To convert the score calculated above, we can work out the minimum and maximum possible score and convert the libraries score into a percentage between those values.

**Ideas for the future:**
Version number over 1.0.0: *Positive*
Supports both iOS & Android: *Positive*
Marked as deprecated: *Negative*
Not updated since a major RN plugin breaking change (like RN 0.40): *Negative*
Native code follows a consistent style (consistent tabbing size etc): *Positive*
JavaScript code follows a consistent style: *Positive*

## Tasks required to get this scoring system in
- [ ] Get the licence from the Github response and add it to the library data.
- [ ] Fetch the README score using the API and add it to the library data
- [ ] Add the scoring rules in a nice way
- [ ] Recalculate the scores
- [ ] Double check that the numbers make sense and adjust the weightings if not
